# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 585)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.startDateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.startDateEdit.setObjectName("startDateEdit")
        self.horizontalLayout.addWidget(self.startDateEdit, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.endDateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.endDateEdit.setObjectName("endDateEdit")
        self.horizontalLayout.addWidget(self.endDateEdit, 0, QtCore.Qt.AlignHCenter)
        self.allRecordsCB = QtWidgets.QCheckBox(self.centralwidget)
        self.allRecordsCB.setObjectName("allRecordsCB")
        self.horizontalLayout.addWidget(self.allRecordsCB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.filterRecord = QtWidgets.QRadioButton(self.centralwidget)
        self.filterRecord.setObjectName("filterRecord")
        self.horizontalLayout_8.addWidget(self.filterRecord)
        self.plotGraph = QtWidgets.QRadioButton(self.centralwidget)
        self.plotGraph.setObjectName("plotGraph")
        self.horizontalLayout_8.addWidget(self.plotGraph)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.filterByHL = QtWidgets.QHBoxLayout()
        self.filterByHL.setObjectName("filterByHL")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filterByHL.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.filterByHL.addWidget(self.label_3)
        self.filterBySpin = QtWidgets.QComboBox(self.centralwidget)
        self.filterBySpin.setObjectName("filterBySpin")
        self.filterByHL.addWidget(self.filterBySpin)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filterByHL.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.filterByHL)
        self.analysisOverHL = QtWidgets.QHBoxLayout()
        self.analysisOverHL.setObjectName("analysisOverHL")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.analysisOverHL.addItem(spacerItem6)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.analysisOverHL.addWidget(self.label_4)
        self.analysisOverSpin = QtWidgets.QComboBox(self.centralwidget)
        self.analysisOverSpin.setObjectName("analysisOverSpin")
        self.analysisOverHL.addWidget(self.analysisOverSpin)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.analysisOverHL.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.analysisOverHL)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.submitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout_5.addWidget(self.submitBtn)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.table = QtWidgets.QTableView(self.centralwidget)
        self.table.setShowGrid(True)
        self.table.setCornerButtonEnabled(True)
        self.table.setObjectName("table")
        self.verticalLayout.addWidget(self.table)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.file_register = QtWidgets.QAction(MainWindow)
        self.file_register.setObjectName("file_register")
        self.addAccount = QtWidgets.QAction(MainWindow)
        self.addAccount.setObjectName("addAccount")
        self.menuFile.addAction(self.file_register)
        self.menuFile.addAction(self.addAccount)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NSWTrafficPenaltyAnalyser"))
        self.label.setText(_translate("MainWindow", "Date: "))
        self.startDateEdit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.label_2.setText(_translate("MainWindow", "To"))
        self.endDateEdit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.allRecordsCB.setText(_translate("MainWindow", "All Records?"))
        self.label_5.setText(_translate("MainWindow", "Operation:"))
        self.filterRecord.setText(_translate("MainWindow", "Filter Records"))
        self.plotGraph.setText(_translate("MainWindow", "Plot a Graph"))
        self.label_3.setText(_translate("MainWindow", "Filter By:"))
        self.label_4.setText(_translate("MainWindow", "Analysis Over: "))
        self.submitBtn.setText(_translate("MainWindow", "Submit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.file_register.setText(_translate("MainWindow", "Register Software..."))
        self.addAccount.setText(_translate("MainWindow", "Add Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

